version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-stretch-node-browsers
    working_directory: ~/AQA-Python-Odessa
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: install allure CLI
          command: |
            uname -a
            sudo npm install -g allure-commandline --save-dev
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python3 -m pytest -n 4 --reruns 2 --alluredir ~/AQA-Python-Odessa/reports/results
      - run:
          name: generate report
          when: always
          command: |
            allure generate -c ~/AQA-Python-Odessa/reports/results -o ~/AQA-Python-Odessa/reports/test_reports
      - store_artifacts:
          path: ~/AQA-Python-Odessa/reports/test_reports
          destination: ~/AQA-Python-Odessa/reports/test_reports
          when: always